networks:
  web:
  db:
services:
  web:
    build:
      context: ./web
      dockerfile: dockerfile
    volumes:
    - ./web:/app
      # - ./web/src:/app/src
      # - ./web/public:/app/public
    ports:
      - "5173:3000"
    networks:
      - web
    env_file:
      - .env
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - web
      - db
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - db