networks:
  web:
  db:
services:
  web:
    build:
      context: ./web
      dockerfile: dockerfile
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    ports:
      - "5173:3000"
    networks:
      - web
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - web
      - db
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 745231968
      MYSQL_DATABASE: nodeprojeto
    networks:
      - db