spring:
  application:
    name: literalura
  datasource:
    url: jdbc:mysql://localhost:3306/literalura
    username: root
    password: 745231968
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      show-sql: true
