/*
 * This source file was generated by the Gradle 'init' task
 */
package projetocod3rcampominado.cm;

import projetocod3rcampominado.cm.modelo.Tabuleiro;
import projetocod3rcampominado.cm.visao.TabuleiroConsole;

public class App {
    public static void main(String[] args) {

        Tabuleiro tabuleiro = new Tabuleiro(6, 6, 6);
        new TabuleiroConsole(tabuleiro);
    }
}
