/*
 * This source file was generated by the Gradle 'init' task
 */
package jdbcdaocod3r;

public class App {
    public static void main(String[] args) {
        Dao dao = new Dao();
        String sql = "INSERT INTO pessoas (nome) VALUES (?)";
        System.out.println(dao.incluir(sql, "João da Silva"));
        System.out.println(dao.incluir(sql, "Joana da Silva"));
        System.out.println(dao.incluir(sql, "Joaquim da Silva"));
        System.out.println(dao.incluir(sql, "Joaquina da Silva"));
        System.out.println(dao.incluir(sql, "Leitão"));
    }
}
