/*
 * This source file was generated by the Gradle 'init' task
 */
package projetocod3rcampominado.cm;

public class App {
    public static void main(String[] args) {
        // Tabuleiro tabuleiro = new Tabuleiro(2, 2, 4);
        
        // tabuleiro.registrarObservador(e -> {
        // if(e.isGanhou()) { 
        //         System.out.println("ganhou");
        //  } else { 
        //     System.out.println("perdeu");
        //  }
        // });

        // tabuleiro.alternarMarcacao(0, 0);
        // tabuleiro.alternarMarcacao(0, 1);
        // tabuleiro.alternarMarcacao(1, 0);
        // tabuleiro.alternarMarcacao(1, 1);
    }
}
