/*
 * This source file was generated by the Gradle 'init' task
 */
package aulaswingcod3r;

import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JFrame;

public class App{
    public static void main(String[] args) {
        JFrame janela = new JFrame("Observador");
        janela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janela.setSize(600,200);
        janela.setLayout(new FlowLayout());
        janela.setLocationRelativeTo(null);

        JButton botao = new JButton("Clicar!");
        janela.add(botao);

        botao.addActionListener(e -> {
            System.out.println("Evento ocorreu, clicado em: " + e.getActionCommand());
        });

        janela. setVisible(true);
    }
}
