version: '3'
services: 
  db:
    image: mongo:3.4

  backend:
    image: node:18
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    command: bash -c "cd /backend && npm install && node app.js"

  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
