/*
 * This source file was generated by the Gradle 'init' task
 */
package javadatabasetest2;

public class App {

    public static void main(String[] args) {
        GeneralTypeMethods.ClearScreen();
        GeneralTypeVariables parClass = new GeneralTypeVariables();
        GeneralTypeMethods.mainLoop(parClass);
    }
}
